// import styles from '../styles/Home.module.css';
import styles from './styles.module.scss';

import { useEffect, useState } from 'react';

import { useForm } from 'react-hook-form';

function App() {
  const { register, handleSubmit, watch } = useForm();
  const [movies, setMovies] = useState([]);
  const [loading, setLoading] = useState(false);
  useEffect(() => {
    randomSearch();
  }, []);
  const randomSearch = async () => {
    setMovies([]);
    setLoading(true);
    const res = await fetch(`/api/searchMovies?random=true`);
    const data = await res.json();
    setMovies(data);
    setLoading(false);
  };
  const handleSearch = async (keyword, column) => {
    setMovies([]);
    setLoading(true);
    const res = await fetch(
      `/api/searchMovies?keyword=${keyword}&column=${column}`
    );
    const data = await res.json();
    setMovies(data);
    setLoading(false);
  };

  const onSubmit = (data) => {
    setLoading(true);
    console.log(data);

    if (data.title === '' && data.search !== 'default') {
      alert(`Please Type ${data.search}`);
      return;
    }
    handleSearch(data?.keyword, data?.column);
  };
  console.log(movies, 'movies');
  return (
    <div className={styles.container}>
      <title>Create Next App</title>

      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />

      <main className={styles.main}>
        <div className={styles.topSection}>
          <h1 className={styles.title}>Welcome to Noogle</h1>
          <h2 className={styles.subtitle}>brought to you by NETFLIX</h2>

          <div className={styles.description}>
            <form className={styles.form} onSubmit={handleSubmit(onSubmit)}>
              <select name='Search by' {...register('column')}>
                <option value='default'>Search By Luck</option>
                <option value='title'>Search By Title</option>
                <option value='startYear'>Search By Start Year</option>
                <option value='genres'>Search By Genres</option>
                <option value='orign_country'>Search By Country</option>
              </select>

              {watch('column') === 'default' ||
              watch('column') === undefined ? (
                <input
                  type='button'
                  onClick={() => randomSearch()}
                  value="I'm feeling lucky"
                />
              ) : (
                <>
                  <input type='text' {...register('keyword')} />
                  <input type='submit' value='SEARCH' />{' '}
                </>
              )}
            </form>
          </div>
        </div>
        {loading ? (
          <p>Loading...</p>
        ) : movies.length === 0 ? (
          <p>No result / Please check your spelling or search option</p>
        ) : (
          <div className={styles.grid}>
            {movies?.map((movie, idx) => {
              return (
                <a
                  href={`https://www.google.com/search?q=${movie.title}`}
                  className={styles.card}
                  target='_blank'
                  rel='noreferrer'
                  key={idx}
                >
                  <div className={styles.movieImageBox}>
                    <img src={movie.image_url} alt={movie.title} />
                  </div>
                  <h2>{movie.title}</h2>
                  <p>Rating: {movie.rating}</p>
                  <p>Year: {movie.startYear}</p>
                  <p>Country: {movie.orign_country}</p>

                  <div className={styles.infoRow}>
                    <span>Votes: {movie.numVotes}</span>
                    <span>Rank: #{movie.popular_rank}</span>
                  </div>
                </a>
              );
            })}
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <p>Built with Nextjs and developed by Hong</p>
      </footer>
    </div>
  );
}

export default App;
